vibrate:
  name: Vibrate Wand
  description: Vibrate Wand
  target:
    device:
      manufacturer: "Warner Bros. Entertainment Inc."
  fields:
    duration:
      name: Duration
      description: Duration of vibrate
      required: true
      example: 500

